version: '3.7'

services:
  stories_db:
    container_name: nodejs_stories_db
    image: postgres:12
    env_file:
      - .env
    ports:
      - '${PG_PORT}:5432'
    expose:
      - '${PG_PORT}'
    environment:
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_DATABASE}
      PG_DATA: /var/lib/postgresql/data
    restart: always
    # to save data between restarts
    volumes:
      - postgresvol:/var/lib/postgresql/data
    networks:
      - stories_db
  elasticsearch:
    image: elasticsearch:8.3.1
    ports:
      - 9200:9200
    networks:
      - es_net
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
  kibana:
    image: kibana:8.3.2
    ports:
      - 5601:5601
    networks:
      - es_net


networks:
  es_net:
  stories_db:
    driver: bridge


volumes:
  postgresvol:
