apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  # config for a pod
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: ark9606/koa-ts-elastic-hex-repo
          ports:
            - containerPort: 3000
          env:
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: pg-password
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: pg-user
            - name: PG_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: postgresql-host
            - name: PG_DATABASE
              value: stories_db
            - name: PG_PORT
              value: '5432'

---
apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
spec:
  type: NodePort # external service
  selector:
    # should match pod label
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80
      # should be the same as containerPort
      targetPort: 3000
      # port from which it will be accessible from the browser
      nodePort: 30001
