apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  # config for a pod
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: pg-password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: pg-user
            - name: POSTGRES_DB
              value: stories_db
            - name: PG_DATA
              value: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP # internal service
  selector:
    # should match pod label
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      # should be the same as containerPort
      targetPort: 5432
