apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  selector:
    matchLabels:
      app: mynodeapp
#  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
        - name: mynodeapp
          # pull from docker hub
          image: ark9606/koa-ts-elastic-hex-repo
          # for k8s to find local docker images
#          imagePullPolicy: Never
          ports:
            - containerPort: 3000
